- requests_cache/backends/storage/dbdict.py
- setup.py
With my application I found many "IntegrityError: column key is not unique" errors. This is because the select statement inside of `__setitem__` wasn't in a transaction with the insert/update. So some other process could come along and add the key between the two statement. Rather than use a transaction I switched to using the "insert or replace into" statement which handles both cases effectively. Also updated `__delitem__` since that one could suffer from a similar problem.
> Better transactional handling in sqlite

- requests_cache/core.py
- tests/test_cache.py
This pull request adds the possibility to exclude some request parameters from the cache key. This is useful in some occasions, for example when requesting the same resources with more access tokens, specified as parameters.
Please let me know if this needs any change to be included in the original project.
> Adding `ignored_parameters` feature

- requests_cache/backends/__init__.py
- tests/test_cache.py
Currently, if you don't have the Python package `redis` intalled
then you get the same message if you type:
requests_cache.install_cache(backend='redis')
as if you type:
requests_cache.install_cache(backend='nonsense!!!!')
> More informative message for missing backend dependencies

- requests_cache/backends/__init__.py
- requests_cache/backends/gridfs.py
- requests_cache/backends/storage/gridfspickledict.py
- tests/test_gridfsdict.py
Hey this support mongo gridfs, which allows file greater than 16MB.
Also, in this new cache store, I named `keys_map` as `http_redirects`  rather than `urls`, there was no document on it, the old name `urls` confused me for a while. I finally figured out what it does by checking the code.
> add gridfs support

- docs/user_guide.rst
I tried the example code, but got:
```
AttributeError: module 'requests_cache' has no attribute 'remove_expired_responses
```
> Fix namespace on remove_expired_responses example

- .travis.yml
The last version of coveralls that I could still install on python2.6 was with `pip install coveralls==1.1`. 
I had sum difficulty even creating the env, as it appears even setuptools and pip have dropped support for python2.6. I think it's reasonable at this point to drop 2.6.
> Fix travis build for python2.6

- .gitignore
- requests_cache/core.py
Say for example you have an API that sets some `error` field in its JSON response, you might want to avoid caching responses which return 200 but have a non-null error field. So you could do something like:
```python
sess = CachedSession(filter_fn=lambda r: r.json().get("error") is None)
```
I toyed with putting this in `send` before caching to make it a generic post-processing function (#98), but I thought that might be confusing to have both functionalities. I could probably make another PR with that feature via a separate mechanimsm if there's interest. 
I'll add some tests when I get a chance, just wanted to get this idea out there.
> Add response filter

- .travis.yml
- setup.py
Python 2.6 is no longer maintained by the Python core team, no longer supported by `pymongo`, and is breaking Travis CI builds
> Remove Python 2.6 Testing

- requests_cache/backends/storage/mongodict.py
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working.
fixes #126
> Fix DeprecationWarning from collections

- requests_cache/backends/storage/dbdict.py
this is required so that the sqlite file size actually decreases after clear (which is probably expected by users).
Cheers,
Olivier
> vacuum the sqlite database after clearing a table

- requests_cache/__init__.py
- requests_cache/compat.py
- requests_cache/core.py
this implements @jhermann's [suggestion](https://github.com/reclosedev/requests-cache/issues/83#issuecomment-368552142).
- fixes #73
- fixes #83
- avoids the need for #102
> Fix handling of unpickle errors

- tests/test_cache.py
Updates #169.
These endpoints formerly returned 302 redirects, but now return 404s. Temporarily disabling these tests for now, using `pytest.mark.skip` (so they still show up in test output as a reminder).
> Temporarily skip tests that depend on httpbin.org/redirect endpoints

- docs/user_guide.rst
- requests_cache/__init__.py
- requests_cache/backends/__init__.py
- requests_cache/backends/base.py
- requests_cache/backends/dynamodb.py
- requests_cache/backends/gridfs.py
- requests_cache/backends/mongo.py
- requests_cache/backends/redis.py
- requests_cache/backends/sqlite.py
- requests_cache/backends/storage/dbdict.py
- requests_cache/backends/storage/mongodict.py
- requests_cache/core.py
- setup.py
- tests/__init__.py
- tests/test_monkey_patch.py
Closes:
* #158 
* #163
* #149 
* #146
* #144  
* #87
Related changes:
* Add sanity checks to get_cache, clear, and remove_expired_responses to make sure requests-cache is installed before calling CachedSession methods
```python
import requests
from requests_cache import CacheMixin, install_cache
from requests_html import HTMLSession
class CachedHTMLSession(CacheMixin, HTMLSession):
"""Session with features from both CachedSession and HTMLSession"""
session = CachedHTMLSession()
r = session.get("https://github.com/")
print(r.from_cache, r.html.links)
```
Or, using the monkey-patch method:
```python
install_cache(session_factory=CachedHTMLSession)
r = requests.get("https://github.com/")
print(r.from_cache, r.html.links)
```
Note that this usage would be more ideal if requests-html could …
> Refactor CachedSession to be usable as a mixin class

- requests_cache/backends/base.py
- requests_cache/backends/dynamodb.py
- requests_cache/backends/gridfs.py
- requests_cache/backends/mongo.py
- requests_cache/backends/redis.py
- requests_cache/backends/sqlite.py
- tests/test_cache.py
This also renames the `BaseCache.keys_map` property and its associated table to `redirects` to make it more clear what it does. This seemed to be a point of confusion on several issues. Also adding info about this to the docs in #191.
> Add property to get all URLs in the cache

- README.md
- docs/advanced_usage.rst
- docs/conf.py
- docs/index.rst
- docs/security.rst
- examples/README.md
- requests_cache/backends/base.py
- requests_cache/backends/sqlite.py
- setup.py
Updates #105; based on feedback from #196
* Move 'Security' section to its own page and link from Readme
* Some other minor edits to Readme examples
* Add `itsdangerous` to default package dependencies
* Show a warning when using `pickle` without `itsdangerous` for Redis, MongoDB, and DynamoDB backends
> Update 'Security' docs and add a warning when using plain pickle with some backends

- HISTORY.md
- requests_cache/backends/__init__.py
- requests_cache/backends/base.py
- requests_cache/cache_keys.py
- requests_cache/core.py
- setup.py
- tests/test_cache.py
Closes #80 and #154
This PR uses [url-normalize](https://github.com/niksite/url-normalize) to improve cache keys. I think it's worth adding the extra dependency, since it's a small library (<6KB) and handles a lot of edge cases that requests-cache doesn't currently handle (resulting in duplicate cached responses in those cases).
This also adds normalization for the request `json` param, as well as JSON-formatted content in `data`.
All utilities related to creating cache keys have been moved to a separate module, `requests_cache.cache_keys`.
> Improve request normalization for generating cache keys

- .readthedocs.yml
- CONTRIBUTING.md
- docs/advanced_usage.rst
- docs/api.rst
- docs/conf.py
- docs/index.rst
- docs/user_guide.rst
- setup.py
**TL;DR:** I'm switching the Sphinx docs to use the [sphinx-material theme](https://bashtage.github.io/sphinx-material/index.html) due to a possible issue with sphinx-rtd-theme. Any other suggestions would be appreciated for how to fix the issue below, or on documentation formatting/theming in general.
For some weird reason, there is currently an issue with the requests-cache docs using sphinx-rtd-theme on readthedocs. It causes almost all bullet lists to not render correctly, which is kind of a dealbreaker:
The same section in sphinx-material, for comparison:
The docs look just fine when built locally, but not on readthedocs, specifically with sphinx-rtd-theme. They look fine on readthedocs with any other theme. I used the `readthedocs/build` docker image and tried various combinations …
> Switch to sphinx-material theme

- CONTRIBUTING.md
- tests/conftest.py
- tests/integration/test_cache.py
This is mainly to make it easier to run a subset of integration tests for RPM package maintainers, or other environments where Docker isn't a viable option. See issue #221.
Usage example (also added to CONTRIBUTING.md):
```bash
pip install pytest-httpbin
export USE_PYTEST_HTTPBIN=true
pytest tests/integration/test_cache.py
```
Other changes:
* Configure logging to show debug output when tests fail (or with `pytest -s`)
* Encountered one minor issue with pytest-httpbin with an easy workaround; made issue https://github.com/kevin1024/pytest-httpbin/issues/60 for this
> Add optional support for pytest-httpbin

- HISTORY.md
- requests_cache/backends/__init__.py
- requests_cache/backends/dynamodb.py
- requests_cache/backends/gridfs.py
- setup.py
- tests/conftest.py
- tests/integration/test_backends.py
- tests/integration/test_dynamodb.py
- tests/integration/test_gridfs.py
- tests/integration/test_mongodb.py
- tests/integration/test_redis.py
- tests/integration/test_sqlite.py
This will address just a couple of the items from #212.
* Update all backend-specific integration tests to fail quickly if not set up, rarther than silently ignoring or hanging
* Add one test case per backend storage class
* Add `aws_access_key_id` and `aws_secret_access_key` kwargs to `DynamoDbDict`
* Made a separate issue to handle this generically for all backends: #229
* Update `GridFSPickleDict.__delitem__` to raise a KeyError for missing items
> Add & update backend integration tests

- requests_cache/response.py
- tests/integration/test_cache.py
- tests/unit/test_response.py
(fixes #232)
Previously, calling `response.raw.read` on encoded responses with `decode_content=False` would (incorrectly) return decoded data, and `decode_content=True` would result in an empty return value or an exception (caused by trying to decode twice).
This change attempts to fix this for the original request that gets modified by `CachedResponse`, by patching `raw.read` to always use `decode_content=False` regardless of the parameter value; this feels kind of hacky (because it is), but I honestly couldn't think of a better way that didn't involve monkey-patching some method of `original_response.raw`.  
The `read` method of `CachedHTTPResponse` is changed in a similar way, discarding the `decode_content` parameter altogether and always returning decoded data directly.  
It should …
> Fix handling of decode_content parameter for raw.read(...)

- HISTORY.md
- requests_cache/backends/base.py
- requests_cache/cache_keys.py
- tests/unit/test_cache.py
Fixes #233 
* Don't pass 'include_get_headers' and 'ignored_parameters' in kwargs to BaseStorage
* Also rename them as public members (no `_` prefix), since they can safely by changed after initialization (e.g., `session.cache.include_get_headers = True`)
> Fix false positive warning with include_get_headers

- docs/conf.py
- requests_cache/backends/__init__.py
- requests_cache/backends/base.py
- requests_cache/backends/dynamodb.py
- requests_cache/backends/gridfs.py
- requests_cache/backends/mongo.py
- requests_cache/backends/redis.py
- requests_cache/backends/sqlite.py
- requests_cache/session.py
- tests/integration/test_dynamodb.py
- tests/integration/test_gridfs.py
- tests/integration/test_mongodb.py
- tests/integration/test_redis.py
- tests/integration/test_sqlite.py
Closes #229, #194
* Pass `**kwargs` to backend storage classes, split out any that are valid for the backend-specific connection function/class, and pass them to the connection
* Add intersphinx links to docs for dependencies
* Update and format some more backend class docstrings
* Remove 'Unrecognized keyword arguments' warning from `BaseStorage`
* Turn `warnings.warn` about using secret keys into a `logging.warning` (due to complaints about too many messages)
> Allow passing any valid backend connection kwargs via BaseCache

- HISTORY.md
- docs/advanced_usage.rst
- requests_cache/backends/base.py
- requests_cache/backends/mongo.py
- requests_cache/backends/sqlite.py
- requests_cache/response.py
- setup.py
- tests/unit/test_cache.py
- tests/unit/test_response.py
Closes #252 , #251
* `BaseCache.keys()`: Get all response and redirect cache keys combined; ignores invalid responses
* `BaseCache.values()`: Get all response objects; ignores invalid responses
* `CachedSession.__str__()`: Get general info about the response and cache expiration
* `CachedSession.__repr__()`: Get a more verbose list of attributes
* `CachedSession.size`: Get human-readable size of response body (also included in `__str__`)
* Update `BaseCache.urls` to return a generator instead of the whole list at once (which may use too much memory for particularly large caches)
* Update `BaseCache.urls` to just skip invalid responses instead of deleting them
* Update changelog and user guide
> Add some more convenience methods for getting cache info

- .gitignore
- HISTORY.md
- examples/generate_test_db.py
- requests_cache/backends/base.py
- requests_cache/backends/sqlite.py
- requests_cache/response.py
- tests/conftest.py
- tests/integration/base_cache_test.py
- tests/integration/test_sqlite.py
- tests/unit/test_cache.py
- tests/unit/test_patcher.py
Follow-up from #240 and #253
* Some minor performance improvements for `remove_expired_responses()` that apply to all backends
* Some additional SQLite-specific improvements
* TODO (in future PRs): Similar bulk delete improvements for the rest of the backends
* Note that `remove_expired_responses()` is still fairly inefficient, in that it deserializes responses to get the expiration time. Optimizing it will require adding an indexed expiration column (and possibly other breaking changes).
* Add an example script to generate a large cache for testing purposes
* Make sure all tests with SQLite dbs clean up after themselves (a few remaining tests weren't yet doing this)
* Remove a couple less useful logging statements
>  Improve performance for remove_expired_responses(), mainly for SQLite backend

- HISTORY.md
- requests_cache/backends/base.py
- requests_cache/backends/dynamodb.py
- requests_cache/backends/mongo.py
- requests_cache/backends/redis.py
- requests_cache/backends/sqlite.py
- tests/integration/base_storage_test.py
Closes #257
* Instead of checking each deleted response for redirects to delete, just delete redirects that point to a non-existing response. In most cases this results in much fewer calls.
* Remove usage of deprecated pymongo `Collection.find_and_modify()`
> Implement a faster bulk delete method for each backend

- requests_cache/session.py
The exception is re-raised, so logging an incomplete traceback at this point makes little sense to me.  Either the caller will catch the exception and log it, or the caller wants the exception suppressed, in which case the incomplete traceback logged here will just confuse them (example: https://github.com/mgedmin/project-summary/issues/3#issuecomment-833257387).
Perhaps logging the original error is useful when `old_data_on_error` is True, in which case I could pass `exc_info=True` to the `logger.warning()` invocation inside the if statement?
> Remove spurious logger.exception()

- .github/pre-commit.yml
- .github/workflows/build.yml
- .github/workflows/deploy.yml
- docs/advanced_usage.rst
- poetry.lock
- pyproject.toml
- requests_cache/response.py
Closes #264.
Interestingly, this uncovered some incompatibilities with older versions of requests, which should be easily fixable.
* Split CI config into separate `build.yml` and `deploy.yml` files (differences explained in comments)
* Skip tests for streaming requests in  `deploy.yml`; appears to require `requests < 2.19`
* Added a note about streaming requests to the docs
* Added minimum requirement `requests >= 2.17`
* **Note:** It may be possible to support versions `2.5-2.16` with some more changes, but I will wait until someone specifically needs this
* Don't attempt to set `PreparedRequest.requests_url` if it's not a valid kwarg (for `requests < 2.19`)
* Use `urllib3.is_fp_closed()` instead of `urllib3.response.HTTPResponse.isclosed()` (for older versions of `urllib3`--unsure which …
> Run tests against multiple versions of requests + compatibility fixes for older requests versions

- docs/user_guide.rst
- poetry.lock
- pyproject.toml
- requests_cache/backends/base.py
- requests_cache/cache_keys.py
- tests/conftest.py
- tests/integration/base_cache_test.py
- tests/performance_test.py
This is an initial implementation of #273 
The library already has functionality for stripping "ignored_parameters" out of a `PreparedRequest` so that those parameters link to the same cached response. As an initial and minimal way of accomplishing #273, essentially the same code used for "ignored_parameters" is also used to strip that information out of a CachedResponse prior to being sent to a backend.
This pull request also includes minor updates necessary to get the tests to pass on a fresh install.
> Remove data in "ignored_parameters" from cached requests

- HISTORY.md
- docs/advanced_usage.rst
- requests_cache/backends/base.py
- requests_cache/models/response.py
- tests/unit/test_session.py
Updates #296
* Add `BaseCache.response_count()` method to get an accurate count of responses (excluding invalid/broken ones)
* Add option to also exclude expired responses in `BaseCache.keys()`, `values()`, and `response_count()`
* Add examples to docs
* Rephrase count in `BaseCache.__str__()` as 'total rows' to be less ambiguous, since the total may include invalid responses
> Add some more options for excluding invalid and expired responses in cache counts

- .github/pre-commit.yml
- HISTORY.md
- poetry.lock
- pyproject.toml
- requests_cache/__init__.py
- requests_cache/models/request.py
- requests_cache/models/response.py
- tests/integration/base_cache_test.py
Updates #320, #321
* Add support for `Response.next` when 302 responses are cached directly                          
* Make `CachedResponse` a non-slotted class to allow client code to set arbitrary attributes on it
> Fixes for CachedResponse attributes

- HISTORY.md
- requests_cache/__init__.py
- requests_cache/backends/filesystem.py
- requests_cache/serializers/preconf.py
- tests/integration/test_filesystem.py
* Pretty-print JSON by default
* Filesystem backend: Add an appropriate file extension to cache files (`.json`, `.yaml`, `.pkl`, etc.) by default.
> Minor improvements for JSON serializer and Filesystem backend

- HISTORY.md
- docs/security.md
- poetry.lock
- pyproject.toml
- requests_cache/backends/filesystem.py
- requests_cache/backends/sqlite.py
- tests/integration/test_filesystem.py
- tests/integration/test_sqlite.py
Adds [appdirs](https://github.com/ActiveState/appdirs) as a dependency. It's a tiny and ubiquitous library, and I think this is a common enough use case that it's worth it.
Can anyone think of a decent parameter name for this? Similar existing options are `use_temp` and `use_memory`.
`use_cache` or `cache_dir` are ambiguous, `use_cache_dir` is too close to (appdirs.)`user_cache_dir`, and `use_user_cache_dir` is rather verbose, and can't think of any better options at the moment.
> Add option to use user cache dir (~/.cache, etc.) for SQLite and Filesystem backends

- HISTORY.md
- requests_cache/cache_keys.py
- tests/unit/test_cache_keys.py
- tests/unit/test_session.py
For shorter cache keys, which is relevant for the filesystem backend, which uses cache keys as filenames. 32 bytes is still more than long enough to prevent hash collisions.
> Use blake2 instead of sha256 for hashing request info

- HISTORY.md
- requests_cache/__init__.py
- requests_cache/backends/base.py
- requests_cache/cache_control.py
- requests_cache/cache_keys.py
- requests_cache/models/__init__.py
- requests_cache/models/request.py
- requests_cache/session.py
- tests/conftest.py
- tests/unit/test_cache_keys.py
- tests/unit/test_session.py
* Handle all normalization in `cache_keys` module, get rid of `normalize_dict()` function used in `CachedSession`
* Reorganize `cache_keys` helper functions into the following:
* `normalize_request()`
* `normalize_url()`
* `normalize_headers()`
* `normalize_params()`
* `normalize_body()`
* `normalize_json_body()`
* `redact_response()`
* Define `__all__` for a couple more modules for star imports
> Reorganize & improve request normalization functions

- HISTORY.md
- examples/benchmark.py
- requests_cache/models/response.py
- tests/unit/test_serializers.py
> Add back overrides for requests.Response.__getstate__ and __setstate__ so plain pickle will work as a serializer

- requests_cache/backends/base.py
- requests_cache/models/response.py
- requests_cache/session.py
- tests/integration/base_cache_test.py
Closes #464 
- Update `CacheMixin`s `_send_and_cache` function to save CachedResponse with updated expiration date upon received 304 before returning the cached value.
- Update `BaseCache`s `save_response` function to only create a `CachedResponse` instance if the argument is not already of type `CachedResponse`
> Fix conditinal request expiration

- HISTORY.md
- requests_cache/cache_keys.py
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>
Closes #<issue number>
> make order of headers repeatable

- HISTORY.md
- requests_cache/serializers/cattrs.py
> Switch to a different method of resolving ForwardRefs during deserialization for python 3.10.2 compatibility

- requests_cache/cache_keys.py
There's no point to decode/encode empty input. It will always fail and original be returned
See https://github.com/reclosedev/requests-cache/issues/494#issuecomment-1028486377
> Skip empty body decode/encode in normalize_json_body

- docs/examples.md
- examples/time_machine_backtesting.py
> Add documentation example for backtesting with time-machine

- HISTORY.md
- pyproject.toml
- requests_cache/serializers/preconf.py
- tests/integration/test_filesystem.py
Fixes #507 (again)
I was previously using  [bson.json_util.dumps()/loads()](https://pymongo.readthedocs.io/en/stable/api/bson/json_util.html), the purpose of which I misunderstood. This PR uses `bson.encode()`/decode()` instead, and correctly sets the serializer type to binary.
**Note:** When the standalone `bson` codec is installed instead of `pymongo`, the functions are named `bson.dumps()/loads()`, which is why the exception was needed in the first place.
> Fix handling BSON serializer differences between pymongo's bson and standalone bson codec

- requests_cache/backends/sqlite.py
- tests/unit/test_session.py
Calling `absolute()` before `expanduser()` results in `~/...` being expanded to `$PWD/~/...` instead of `/home/user/...`.
> Fix cache path expansion

- HISTORY.md
- docs/user_guide/compatibility.md
- docs/user_guide/expiration.md
- docs/user_guide/headers.md
- pyproject.toml
- requests_cache/__init__.py
- requests_cache/backends/base.py
- requests_cache/cache_control.py
- requests_cache/models/response.py
- requests_cache/patcher.py
- requests_cache/session.py
- setup.cfg
- tests/conftest.py
- tests/integration/base_cache_test.py
- tests/integration/base_storage_test.py
- tests/unit/models/test_response.py
- tests/unit/test_base_cache.py
- tests/unit/test_cache_control.py
- tests/unit/test_session.py
Closes #541, closes #539, closes #546, closes #547
* Add `refresh` option to `CachedSession.request()` and `send()`
* Add `revalidate` option to `CachedSession.request()` and `send()`
* Revalidate for `Cache-Control: no-cache` request or response header
* Revalidate for `Cache-Control: max-age=0, must-revalidate` response headers
* Fix some incorrect wording about revalidation in docs
> Add additional revalidation conditions, and new keyword arguments for request() and send()

- HISTORY.md
- docs/user_guide/expiration.md
- docs/user_guide/headers.md
- requests_cache/cache_control.py
- requests_cache/session.py
- tests/unit/test_session.py
> Add support for Cache-Control: only-if-cached and corresponding options for request() and send()

- poetry.lock
- pyproject.toml
- requests_cache/serializers/preconf.py
It seems in the latest release of cattrs, its preconf modules no longer catches ImportErrors for missing dependencies, so doing that on our end instead.
Also did a bit of cleanup in the serializers.preconf module (no more nested try-except blocks).
> Add compatibility with cattrs 21.1

- .pre-commit-config.yaml
- HISTORY.md
- docs/user_guide/expiration.md
- docs/user_guide/filtering.md
- examples/url_patterns.py
- requests_cache/__init__.py
- requests_cache/_utils.py
- requests_cache/backends/base.py
- requests_cache/cache_control.py
- requests_cache/expiration.py
- requests_cache/session.py
- requests_cache/settings.py
- tests/conftest.py
- tests/unit/test_cache_control.py
- tests/unit/test_expiration.py
- tests/unit/test_patcher.py
- tests/unit/test_session.py
More refactoring of cache settings and policy logic, continuing from #555.
* Fix a bug in which some kwargs specific to requests-cache could get passed to `requests.Session.send()`
* Rename two (unreleased) options to be more consistent with browser behavior:
* `revalidate()` -> `refresh()`
* `refresh()` -> `force_refresh()`
* Revert `RequestSettings` changes and use just kwargs instead for per-request settings
* Add full type hints back to extra kwargs for `CachedSession.send()`
* Use 'must-revalidate' as a temporary header for a user-requested refresh
* Use expiration value of 0 more accurately as 'expire immediately' rather than 'do not cache'
* Behavior is now the same as `Cache-Control: max-age=0`
* It may potentially be saved and used with revalidation, depending on other …
> Revise behavior for refresh, force_refresh, and DO_NOT_CACHE

- HISTORY.md
- examples/generate_test_db.py
- requests_cache/backends/base.py
- requests_cache/backends/sqlite.py
- tests/integration/test_sqlite.py
- tests/unit/test_patcher.py
- tests/unit/test_session.py
Closes #364
**Note:** There may still be more improvements to make here, so this will likely change somewhat before release.
This adds a significantly more efficient implementation of `remove_expired_responses()` for SQLite. This does modify the table structure (new column + index), but retains backward-compatibility by updating tables created in previous versions of requests-cache.
Based on some quick benchmarks, this appears to result in a speedup of over 10x.
This also adds a `sorted()` method for the SQLite backend, which allows sorting responses by size or expiration. Also allows a query limit, reverse order, and excluding expired responses.
> Improve performance for cache eviction in SQLite backend

- HISTORY.md
- docs/reference.md
- pyproject.toml
- requests_cache/__init__.py
- requests_cache/backends/base.py
- requests_cache/backends/mongodb.py
- requests_cache/backends/sqlite.py
- requests_cache/cache_keys.py
- requests_cache/models/response.py
- requests_cache/patcher.py
- requests_cache/policy/__init__.py
- requests_cache/policy/actions.py
- requests_cache/policy/directives.py
- requests_cache/policy/expiration.py
- requests_cache/policy/settings.py
- requests_cache/serializers/__init__.py
- requests_cache/session.py
- tests/integration/test_mongodb.py
- tests/unit/policy/test_actions.py
- tests/unit/policy/test_expiration.py
- tests/unit/test_session.py
This subpackage now basically contains everything that was formerly in the `cache_control` module as of 0.9, plus everything that has been added since then. With all the new cache header-related features that have been added, that module was getting a bit too complicated.
I don't believe this will break any client code, unless someone was importing directly from `requests_cache.cache_control`. This has been added to the changelog just in case, though.
* `requests_cache.policy.directives`: Parses request/response headers
* `requests_cache.policy.expiration`: Parses and converts all the various expiration formats
* `requests_cache.policy.settings`: Cache behavior settings that may be set on `CachedSession`
* `requests_cache.policy.actions`: Uses all of the above to translates session …
> Add CacheDirectives class and move all cache policy-related modules under a new 'policy' subpackage

- HISTORY.md
- requests_cache/backends/base.py
- requests_cache/backends/mongodb.py
- requests_cache/backends/redis.py
- requests_cache/session.py
- tests/integration/base_cache_test.py
Closes #588
Applies to:
* SQLite
* MongoDB/GridFS
* Redis
> Close database connections on contextmanager exit or session.close() 

- HISTORY.md
- docs/user_guide/backends/filesystem.md
- docs/user_guide/backends/redis.md
- docs/user_guide/expiration.md
- requests_cache/backends/__init__.py
- requests_cache/backends/base.py
- requests_cache/backends/dynamodb.py
- requests_cache/backends/filesystem.py
- requests_cache/backends/gridfs.py
- requests_cache/backends/mongodb.py
- requests_cache/backends/redis.py
- requests_cache/backends/sqlite.py
- requests_cache/models/response.py
- requests_cache/serializers/__init__.py
- requests_cache/serializers/pipeline.py
- requests_cache/serializers/preconf.py
- requests_cache/session.py
- tests/integration/base_cache_test.py
- tests/integration/base_storage_test.py
- tests/integration/test_dynamodb.py
- tests/integration/test_mongodb.py
- tests/integration/test_sqlite.py
- tests/unit/test_base_cache.py
- tests/unit/test_session.py
Closes #609 
This also fixes an issue with expiration in the SQLite backend: the current time was being set using `datetime.utcnow().timestamp()`, which is apparently not a reliable way to get Unix time. Now just using `time.time()`
> Merge serializer-specific storage classes into respective parent classes

- HISTORY.md
- poetry.lock
- pyproject.toml
- requests_cache/backends/dynamodb.py
- requests_cache/backends/mongodb.py
- requests_cache/backends/redis.py
- requests_cache/backends/sqlite.py
- tests/integration/test_mongodb.py
Updates #611. This backports the fix in #612 for v0.9.
> Fix forwarding connection parameters for redis-py 4.2 and pymongo 4.1 on python <=3.8

- requests_cache/patcher.py
> (0.9) Initialize backend with install_cache() prior to patching requests.Session

- HISTORY.md
- requests_cache/models/request.py
- tests/unit/models/test_request.py
Updates #636 (backporting to 0.9)
> (0.9) Add CachedRequest.path_url property

- requests_cache/_utils.py
- requests_cache/models/base.py
- requests_cache/models/raw_response.py
- requests_cache/models/request.py
- requests_cache/models/response.py
- requests_cache/policy/actions.py
- requests_cache/policy/directives.py
- requests_cache/policy/settings.py
- tests/integration/test_compat.py
- tests/unit/models/test_base.py
- tests/unit/test_serializers.py
Instances of some of these classes are fairly useful to have in debug logs, especially `CacheActions` to show exactly what criteria were used to read or write something from the cache. It gets a bit verbose, though.
I previously made some changes for better output when logged with `rich`. This does the same thing without `rich` installed, and condenses the output to exclude any default values. So instead of:
```python
>>> repr(CacheActions(resend_async=True))
'CacheActions(error_504=False, expire_after=None, send_request=False, resend_request=False, resend_async=True, skip_read=False, skip_write=False)'
```
It now looks like:
```python
>>> repr(CacheActions(resend_async=True))
'CacheActions(resend_async=True)'
```
> Condensed repr for attrs classes

- HISTORY.md
- docs/user_guide/expiration.md
- docs/user_guide/inspection.md
- examples/generate_test_db.py
- requests_cache/backends/base.py
- requests_cache/backends/filesystem.py
- requests_cache/backends/gridfs.py
- requests_cache/backends/sqlite.py
- requests_cache/models/response.py
- requests_cache/patcher.py
- requests_cache/session.py
- tests/conftest.py
- tests/integration/base_cache_test.py
- tests/unit/test_base_cache.py
- tests/unit/test_patcher.py
- tests/unit/test_session.py
Closes #643, updates #622, updates #651
New `BaseCache` method signatures:
```python
def remove(
expired: bool = True,
invalid: bool = True,
older_than: datetime = None,
):
...
def reset_expiration(expire_after: ExpirationTime = None):
...
```
`BaseCache.remove_expired_responses()` is still available, but marked as deprecated.
> Split up remove_expired_reponses() into more granular methods and arguments

- HISTORY.md
- requests_cache/backends/base.py
- requests_cache/backends/sqlite.py
- requests_cache/models/raw_response.py
- requests_cache/models/response.py
- requests_cache/serializers/cattrs.py
- requests_cache/serializers/pipeline.py
- tests/integration/test_filesystem.py
- tests/integration/test_sqlite.py
Closes #653
* Use more efficient SQL query in SQLiteCache if using `.filter()` for expired responses only
* Remove `SerializerPipeline.decode_content` property, just make it a setter method
* Remove (redundant) HTTPResponse attributes from the cache
* Reconstruct CachedResponse.raw after deserialization
> Misc cleanup

- requests_cache/cache_keys.py
- tests/unit/test_cache_keys.py
Updates #677 
This adds support for requests that differ only by a duplicated request param (e.g, `a=1` vs `?a=1&a=2`)
> Add support for duplicate request params

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- HISTORY.md
- requests_cache/backends/base.py
- requests_cache/models/response.py
- tests/conftest.py
- tests/unit/test_base_cache.py
- tests/unit/test_patcher.py
- tests/unit/test_session.py
* Run pre-deploy stress tests as a separate job
* Run pre-deploy unit tests for all supported combinations of platforms, python versions, and requests versions
* Add option to run pre-deploy tests without publishing to PyPI
* Silence DeprecationWarnings during tests for deprecated methods
* Fix issue on Windows with occasional missing `CachedResponse.created_at` timestamp
> Improvements for deployment workflow

- HISTORY.md
- docs/user_guide/expiration.md
- docs/user_guide/inspection.md
- requests_cache/backends/base.py
- tests/integration/base_cache_test.py
- tests/integration/test_mongodb.py
- tests/unit/test_base_cache.py
- tests/unit/test_session.py
Basically this is just to add a shortcut for checking/deleting a simple GET request by URL, similar to the `has_url()` and `delete_url()` methods that `contains()` and `delete()` have replaced.
> Add 'url' argument to BaseCache.contains() and delete()

- requests_cache/session.py
Fairly straightforward? I don't think `remove` even exists, and I assume it means to say `delete`.
> Fix remove_expired_responses deprecation suggestion

- HISTORY.md
- requests_cache/backends/base.py
- requests_cache/backends/sqlite.py
- requests_cache/session.py
- tests/compat/test_requests_mock_load_cache.py
- tests/compat/test_responses_load_cache.py
- tests/unit/test_base_cache.py
Updates #704.
Along with #710, this fixes some possible issues with upgrading from 0.9 to 1.0
> Minor backwards compatibility changes

- HISTORY.md
- requests_cache/__init__.py
- requests_cache/backends/__init__.py
- requests_cache/backends/base.py
- requests_cache/cache_control.py
- requests_cache/models/response.py
- requests_cache/patcher.py
- requests_cache/policy/__init__.py
- requests_cache/policy/actions.py
- requests_cache/session.py
- tests/unit/policy/test_actions.py
> Add forwards-compatibility and some DeprecationWarnings for some upcoming changes between 0.9 and 1.0

- requests_cache/serializers/cattrs.py
- tests/unit/test_serializers.py
Related to #719
This could happen in one of two cases:
* A version of `cattrs` is installed older than the minimum pinned version (22.2)
* A custom serializer is made using `BaseConverter`
> Handle using a converter that doesn't support `omit_if_default`

- HISTORY.md
- requests_cache/backends/base.py
- requests_cache/backends/sqlite.py
- tests/integration/base_cache_test.py
- tests/integration/test_sqlite.py
- tests/unit/test_base_cache.py
- tests/unit/test_session.py
Closes #722
* Improve `SQLiteCache.sorted()`: exclude any invalid responses
* Add a `SQLiteCache.count()` method to count responses, with option to exclude expired responses (performs a fast indexed count instead of slower in-memory filtering)
* Make use of index with `SQLiteCache.filter(expired=False)`
* Set `uri=True` when using an in-memory SQLite db
> Sqlite improvements

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- HISTORY.md
- noxfile.py
- tests/conftest.py
- tests/integration/base_cache_test.py
- tests/integration/test_sqlite.py
- tests/unit/test_session.py
Closes #733, updates #753
Looks like pypy + requests-cache gets some unexpected `OperationalError` (database locked) due to a very different implementation of the `sqlite3` module that doesn't seem to provide the same concurrency support as the stdlib `sqlite3` module.
For now, I am disabling running pypy tests in parallel, and skipping a few specific tests.
> Add tests for pypy3.9

- requests_cache/backends/base.py
- requests_cache/backends/dynamodb.py
- requests_cache/backends/filesystem.py
- requests_cache/backends/gridfs.py
- requests_cache/backends/mongodb.py
- requests_cache/backends/redis.py
- requests_cache/backends/sqlite.py
- requests_cache/serializers/__init__.py
- tests/integration/base_cache_test.py
- tests/integration/base_storage_test.py
- tests/integration/test_dynamodb.py
- tests/integration/test_filesystem.py
- tests/integration/test_mongodb.py
- tests/integration/test_redis.py
This sets default serializers for each backend using param defaults instead of 'default_serializer' class attributes. This requires an extra check in the `__init__()` method of each backend class, but I think it's now a bit easier to follow.
Also, I wasn't quite happy with adding an extra `no_serializer` param to disambiguate between `serialzier=None` (keyword arg default) and explicitly disabling the serializer.
> Change initialization for backend-specific default serializers

- HISTORY.md
- requests_cache/policy/actions.py
- tests/unit/policy/test_actions.py
- tests/unit/test_session.py
Backporting #763 for v0.9
Fixes #762
> Raise an error for invalid expiration string values (v0.9)

- HISTORY.md
- requests_cache/policy/expiration.py
- tests/unit/policy/test_expiration.py
- tests/unit/test_session.py
(except for headers containing httpdates)
Fixes #762
> Raise an error for invalid expiration string values 

- HISTORY.md
- docs/user_guide/expiration.md
- requests_cache/policy/__init__.py
- requests_cache/policy/expiration.py
- requests_cache/policy/settings.py
- tests/unit/policy/test_expiration.py
This allows for more fine-grained control over URL patterns than globbing in the rare cases where that is needed.
> Allow regexes for URL expiration patterns

- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/unit/test_base_cache.py
- tests/unit/test_session.py
This fixes flaky test behavior like this: https://github.com/requests-cache/requests-cache/actions/runs/4516275647/jobs/7954969801
It seems that the slow performance when running many CI jobs in parallel is enough to cause some expiration-related tests to occasionally fail if they depend on timing.
> Use time-machine instead of sleep for timing-based tests

- HISTORY.md
- requests_cache/backends/base.py
- tests/unit/test_base_cache.py
> Fix `BaseCache.recreate_keys()` to normalize response bodies with `b'None'`

- HISTORY.md
- requests_cache/policy/actions.py
- requests_cache/serializers/cattrs.py
- tests/conftest.py
- tests/unit/test_session.py
> Fix request matching with Vary and redirects

- HISTORY.md
- docs/user_guide/backends/sqlite.md
- poetry.lock
- pyproject.toml
- requests_cache/__init__.py
- requests_cache/backends/base.py
- requests_cache/backends/sqlite.py
- requests_cache/policy/actions.py
- requests_cache/session.py
- tests/integration/test_sqlite.py
- tests/unit/test_session.py
Updates #820, plus some other misc improvements for multithreading:
- Add `busy_timeout` argument for `SQLiteCache`
- Use lock contextmanager in `SQLiteDict.connection` to ensure it's always released
- Previously, using `acquire()`, `commit()`, and `release()` wouldn't correctly release the lock if there was an exception during COMMIT
- Manually close cursor after SELECT to avoid issues with accessing row variable outside of connection contextmanager
- Weird `UnboundLocalError` occasionally seen with multithreading and high request rates
- Add lock around SQLite db initialization and closing
- Avoids multiple threads trying to create tables at startup
- Reuse the same lock object for both SQLite tables
- Avoid unnecessary cache writes for revalidation requests if headers and expiration …
> SQLite multithreading improvements

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- HISTORY.md
- requests_cache/backends/sqlite.py
- tests/integration/test_sqlite.py
> Allow disabling vacuum for SQLiteCache.delete(), and skip by default if only deleting one key

- HISTORY.md
- examples/time_machine_backtesting.py
- requests_cache/models/response.py
- requests_cache/policy/actions.py
- requests_cache/policy/expiration.py
- tests/conftest.py
- tests/integration/base_cache_test.py
- tests/integration/test_sqlite.py
- tests/unit/models/test_response.py
- tests/unit/policy/test_actions.py
- tests/unit/policy/test_expiration.py
- tests/unit/test_base_cache.py
- tests/unit/test_session.py
This makes the `now`s timezone-aware, as demanded by Python 3.12+.
Towards fixing #845.
> Use timezone-aware expiration datetimes

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- HISTORY.md
- noxfile.py
- poetry.lock
- pyproject.toml
> Drop support for Python 3.7

- docs/project_info/related_projects.md
First and foremost, thank you for this fantastic package, which inspired me to create [Hishel](https://hishel.com).
I saw that [httpx-cache](https://github.com/obendidi/httpx-cache) recommends switching to Hishel, and since you have a section where you put related projects, I thought it would be useful to update the httpx caching package to the new one.
> Change httpx-cache to Hishel

- HISTORY.md
- docs/user_guide/filtering.md
- requests_cache/cache_keys.py
- requests_cache/policy/actions.py
- requests_cache/policy/directives.py
- tests/unit/test_session.py
Closes #830
Adds support for the following nonstandard request headers (case-insensitive):
* `X-HTTP-Method-Override`
* `X-HTTP-Method`
* `X-Method-Override`
If the method specified by one of these headers is in `allowable_methods`, it will pass the check for both cache read and write.
> Add support for HTTP method override headers

- HISTORY.md
- poetry.lock
- requests_cache/models/response.py
- requests_cache/serializers/cattrs.py
- requests_cache/serializers/preconf.py
- tests/benchmark_serializers.py
- tests/conftest.py
- tests/integration/base_cache_test.py
- tests/integration/test_dynamodb.py
- tests/unit/test_serializers.py
#907, fixes #868
Note: after refactoring handling of `decode_content`, an issue came up with the DynamoDB backend with serializing a JSON body with float values. These need to be converted to Decimals, but I couldn't figure out a way to integrate this into the existing converter. I added a (hopefully) temporary workaround for this.
> Fix for compatibility with cattrs 23.2

- HISTORY.md
- requests_cache/_utils.py
TIL: According to RFC 2046, a form boundary in a multipart request can only include "characters known to be very robust through mail gateways" (as of 1996?):
```c
boundary := 0*69<bchars> bcharsnospace
bchars := bcharsnospace / " "
bcharsnospace := DIGIT / ALPHA / "'" / "(" / ")" /
"+" / "_" / "," / "-" / "." /
"/" / ":" / "=" / "?"
```
Fixes #917
> Replace unsupported characters in patched form boundary

- requests_cache/models/base.py
- requests_cache/models/raw_response.py
- requests_cache/models/request.py
- requests_cache/models/response.py
- requests_cache/policy/actions.py
- requests_cache/policy/directives.py
- requests_cache/policy/settings.py
- tests/unit/models/test_base.py
> Consistently use 'attrs' namespace instead of 'attr'

- README.md
- docs/user_guide/expiration.md
Updates #890
Added a "Resetting Expiration" section, linked from the top of the [Expiration](https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html) page in the docs.
> Clarify behavior for updating expiration settings

- HISTORY.md
- requests_cache/cache_keys.py
- tests/unit/test_session.py
> Store `verify=True` and `verify=cert path` under same cache key

- requests_cache/models/raw_response.py
The following situation triggered `IncompleteRead` error with `urllib3>=2.0`, same way as [here](https://github.com/psf/cachecontrol/issues/295): 
```
pip install omnipath requests_cache
```
```
import requests_cache
requests_cache.install_cache('foobar')
import omnipath as op
```
The import of `omnipath` issues some downloads by `requests` the following way (I tried to create a minimal reproducible example based on the [code here](https://github.com/saezlab/omnipath/blob/main/omnipath/_core/downloader/_downloader.py)):
```
from requests import Request, Session
from requests.adapters import HTTPAdapter
from urllib3.util import Retry
from io import BytesIO
from tqdm import tqdm
import requests_cache
requests_cache.install_cache('foobar')
url = 'https://omnipathdb.org/about'
session = …
```
> reset `_fp_bytes_read` and `length_remaining` on raw response to avoid `Incompleteread` with `urllib3` 2.x

- docs/user_guide/expiration.md
Stray apostrophe detected:
- https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html
> Fix typo in doc/expiration.md

- HISTORY.md
- requests_cache/models/response.py
Closes #975
Example to manually verify consistency:
```py
from requests_cache import CachedResponse
from datetime import datetime
r = CachedResponse(expires=datetime.now())
timestamps = {r.expires_unix for _ in range(10000000)}
assert len(set(timestamps)) == 1
```
> Fix inconsistency due to rounding in CachedResponse.expires_unix property

- requests_cache/_utils.py
Requests_cache version 1.2.0 causes our server to respond with error 400 on multipart requests.
After some investigation, i tracked this down to PR #919:
With the older format i get a proper response (status 200): `FORM_BOUNDARY = '##requests-cache-form-boundary##'`
With the new format i get error 400: `FORM_BOUNDARY = '==requests-cache-form-boundary=='`
I'm not very experienced with requests, but to my understanding [RFC2046](https://www.rfc-editor.org/rfc/rfc2046#section-5.1.1) suggests "The boundary delimiter line is then defined as a line consisting entirely of two hyphen characters ("-", decimal value 45) [...]"
So, i tested replacing the "==" with hyphens "--" in the below formats:
1. `FORM_BOUNDARY = '--requests-cache-form-boundary--'`
2. `FORM_BOUNDARY = …
> Fixes error 400 responses from patched form boundary

- HISTORY.md
- tests/compat/test_responses_load_cache.py
Fixes #990
In `requests` 2.32, `HTTPAdapter.get_connection()` can no longer be used to detect a real request made (with the default `verify=True`). The fix is to use `get_connection_with_tls_context()` instead.
That being said, a potential improvement for this example/test would be to use a lower-level/client-agnostic way to detect a real request made.
> Fix usage example/test with `responses` library to be compatible with `requests` 2.32

- HISTORY.md
- requests_cache/serializers/cattrs.py
- tests/integration/base_cache_test.py
Fixes #963
This was a painful one. After a couple attempts at diving deep into debugging serialization logic and finding nothing, I later found that it was a simple case of testing `if x` instead of `if x is None`. 🤦
> Fix loading cached JSON content with `decode_content=True` when the root element is empty

- HISTORY.md
- requests_cache/backends/base.py
- tests/unit/test_base_cache.py
> Add `verify` parameter to `BaseCache.contains()` and `delete()` to handle requests made with SSL verification disabled

- HISTORY.md
- requests_cache/models/response.py
- requests_cache/policy/expiration.py
- tests/unit/models/test_response.py
> Ignore and log timezone errors when attempting to reuse responses cached in `requests-cache <= 1.1`

- HISTORY.md
- docs/user_guide/serializers.md
- poetry.lock
- pyproject.toml
- requests_cache/_utils.py
- requests_cache/backends/filesystem.py
- requests_cache/serializers/__init__.py
- requests_cache/serializers/preconf.py
- tests/unit/test_serializers.py
Closes #994
Changes:
* Changed behavior for `serializer='json'`, depending on installed packages:
* Priority: `orjson` -> `ujson` -> stdlib `json`
* Added the following serializers to explicitly use a specific JSON library: `json_serializer`, `ujson_serializer`, and `orjson_serializer`
> Improve support for `orjson`; Add explicit serializers for `json`, `ujson`, and `orjson`

- .gitignore
- HISTORY.md
- docs/user_guide/serializers.md
- pyproject.toml
- requests_cache/backends/filesystem.py
- requests_cache/serializers/__init__.py
- requests_cache/serializers/preconf.py
- tests/integration/test_filesystem.py
- tests/unit/test_serializers.py
Closes #951; follow-up from #994, #997, #999
* Remove automatic selection of JSON library; require specifying it explicitly
* Drop support for standalone `bson` codec; require pymongo's `bson` module
* Use `.bson` file extension by default when using BSON serializer with filesystem backend
* Remove `[bson]` and `[json]` package extras
> Changes to JSON and BSON serializers

- requests_cache/patcher.py
In my IDE this line was nagging me, and I saw that `install_cache` only accepted a `str`. But both `init_backend` and `CacheMixin` allows a `StrOrPath` as their input.
So this one brings the typing in line with the methods that are being called (and stopping my IDE warning not to provide paths ;)).
> Improve type hinting by also allowing `Path`s to be correct when installing the cache

- .github/pull_request_template.md
Inside the PR template there was a wrong link present (I checked during the creation of my previous one).
As that was unrelated to that PR, creating one to correct the link.
> Wrong link corrected in the PR template

- HISTORY.md
- requests_cache/patcher.py
- requests_cache/policy/settings.py
- requests_cache/session.py
- tests/unit/test_patcher.py
- tests/unit/test_session.py
Fixes #1034
* Defaults to `True` when using `CachedSession` (typically long-lived session objects; same as current behavior)
* Defaults to `False` when using `install_cache()` (short-lived session objects, one per request; changed behavior)
> Add `autoclose` option to close backend connections when the session is closed

- HISTORY.md
- requests_cache/policy/actions.py
- requests_cache/policy/directives.py
- requests_cache/policy/expiration.py
- tests/unit/policy/test_expiration.py
- tests/unit/test_session.py
Closes #1014
This ensures that `DO_NOT_CACHE` remains an internal value only and isn't sent in request headers. The challenge here was that there is no way to pass extra arbitrary parameters from `CachedSession.request()` -> `Session.request()` -> `CachedSession.send()`, so `DO_NOT_CACHE` was being passed via `Cache-Control: max-age` (same as any other per-request `expire_after` value).
This PR's inelegant solution is to pass this value via an arbitrary, non-standard header `X-ACTUAL-NO-CACHE` (not to be confused with `Cache-Control: no-cache`... which of course doesn't actually mean what it says), and then remove it in `CachedSession.send()` before sending the actual request.
If anyone has ideas for a better way to accomplish this, I'm open to suggestions!
> Fix request headers sent when `expire_after` is set to `DO_NOT_CACHE`

- CONTRIBUTING.md
- HISTORY.md
- tests/conftest.py
This re-orders the development setup so that all commands should run successfully. Also USE_PYTEST_HTTP_BIN now raises an error if not installed but in use.
Closes #1056 
Obsoletes #1051
> Reorder development setup

- requests_cache/backends/sqlite.py
- tests/integration/test_sqlite.py
in the sqlite backend, the current strategy for writes is to write-with-retry. however, this can fail because our connection could be starved for a write if we are racing with other processes and sqlite keeps giving the write to other processes.
this commit addresses the issue by acquiring an exclusive lock from sqlite before any write to the database.
references:
- https://stackoverflow.com/a/21888761
- https://www.sqlite.org/lockingv3.html
if my understanding is correct, this closes #820
> fix: sqlite write contention

- HISTORY.md
- requests_cache/backends/redis.py
- tests/integration/base_cache_test.py
> Use `SCAN` and `HSCAN` instead of `KEYS`, `HKEYS`, and `HGETALL`

- HISTORY.md
- requests_cache/policy/actions.py
- requests_cache/serializers/cattrs.py
- tests/unit/policy/test_actions.py
> When updating response headers after revalidating a cached response, don't set both `Content-Length` and `Transfer-Encoding`

- HISTORY.md
- requests_cache/backends/sqlite.py
- tests/integration/test_filesystem.py
- tests/integration/test_sqlite.py
Closes #845
This is a workaround to resolve `sqlite3.InterfaceError: bad parameter or other API misuse` errors when using the SQLite backend concurrently on python 3.12.  This doesn't quite address the root cause, which is still baffling to me. I suspect it's a bug in the cpython `sqlite` module, but I don't have the capability to debug further.
This uses string formatting instead of DBAPI parameter placeholders, which generally isn't good practice, but I believe there is no practical risk of SQL injection since it's just inserting cache keys generated by the library itself.
> Fix SQLite concurrency on python 3.12+

- HISTORY.md
- requests_cache/policy/expiration.py
- tests/unit/policy/test_expiration.py
Closes #1090
Debating about how to fix this as this function looks to be used for headers other than just expires.
Originally I just amended the ValueError to `return start_time or utcnow()` but you seem to want this behaviour according to your unit tests so instead I went with a 'pre-massaging' step to change integer strings to `EXPIRE_IMMEDIATELY`.
> for Expires, an invalid date must be treated as 'already expired'

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- docker-compose.yml
- tests/conftest.py
- tests/integration/base_cache_test.py
Fixes #1085
Minor differences:
* default port is 8080, not 80
* `/cookies` endpoint uses request params instead of paths to set cookie values (e.g., `/cookies/set/k/v` -> `/cookies/set?k=v`)
* does not have brotli support
> Switch from httpbin Docker image to go-httpbin for arm64/Apple silicon support

- HISTORY.md
- requests_cache/cache_keys.py
- tests/unit/test_cache_keys.py
This implementation allows to use requests_cache on any FIPS-compliant systems and systems where limited OpenSSL blake2b implementation is invoked.
Note: there is `usedforsecurity` keyword argument for hashlib that can allow usage of `blake2b` on FIPS-compliant systems, but  1) it requires Python 3.9 and 2) it does not solve the issue with lacking OpenSSL blake2b implementation.
> Use SHA256 as a fallback hashing algorithm on FIPS-enabled systems

- HISTORY.md
- docs/user_guide/backends/dynamodb.md
- requests_cache/backends/dynamodb.py
- tests/integration/test_dynamodb.py
This is a backwards compatible change that makes dynamodb table creation optional. Will high levels of load this was leading to API throttling errors for the dynamodb create table api. Solves https://github.com/requests-cache/requests-cache/issues/1027
Closes #1027
> feat: make table creation optional

- docs/conf.py
- pyproject.toml
- uv.lock
Add [sphinx-sitemap](https://github.com/jdillard/sphinx-sitemap) and [sphinx-llms-txt](https://github.com/jdillard/sphinx-llms-txt).
**Note:** A current limitation is that rST directives like `automodule::` are not rendered, so `llms-full.txt` does not contain API docs. One option may be to generate this from the sitemap, using a tool like [llmstxt](https://github.com/dotenvx/llmstxt).
> Generate sitemap.xml and llms.txt

- .github/workflows/build.yml
- noxfile.py
In CI, SQLite concurrency tests recently started failing on python 3.13 (Disk or other I/O errors), and concurrency tests for a few other backends are occasionally flaky in general. Running these tests separately without xdist appears to fix or reduce this.
> Fix flaky tests in CI

- .github/workflows/build.yml
- HISTORY.md
- pyproject.toml
- tests/conftest.py
- tests/integration/test_mongodb.py
- tests/integration/test_redis.py
- uv.lock
The multiprocessing-based timeout method used by `timeout-decorator` now raises `PicklingError` on python 3.14 when used with pytest-xdist, so this change replaces it with a threading-based version.
> Run tests for python 3.14 and fix multiprocessing `PicklingError`
