requests-cache/requests-cache

requests_cache/backends/base.py, requests_cache/compat.py, requests_cache/core.py, tests/test_cache.py
trying to fix my issue with the ignored_parameters option as described in #52
not sure if it is all correct, but tests seem to work
please review
edit: refactored it a bit to be less invasive on the existing code
=> remove ignored parameters only from cachekeys

requests_cache/backends/storage/mongodict.py
=> Added support for pymongo 3, Add collection_name arg to MongoCache

requests_cache/backends/__init__.py, requests_cache/backends/dynamodb.py, requests_cache/backends/storage/dynamodbdict.py, tests/test_dynamodbdict.py
This pull request is aim to support dynamodb as backend.
I want to use this library in AWS Lambda environtment.
=> add dynamodb backend

requests_cache/backends/storage/dbdict.py
=> Fix warning on python3.7 and import on python3.8

requests_cache/backends/storage/dynamodbdict.py, requests_cache/backends/storage/gridfspickledict.py, requests_cache/backends/storage/redisdict.py
=> Fix DeprecationWarning about collections.MutableMapping

requests_cache/backends/storage/mongodict.py
=> Addressing mongodb .save deprecation warning

requests_cache/backends/storage/dbdict.py, requests_cache/core.py
Hi !
Juste made some imports relative, useful when the lib is installed manually.
I made the changes online and didn't test, so merge carefully !
Cheers !
Olivier
=> Relative imports

requests_cache/backends/base.py
=> Avoiding iteration error when using BaseCache from multiple threads

requests_cache/core.py, tests/test_cache.py
This is a follow-up for PR #20 which can be automatically merged now.
=> Return date of cached response

.github/workflows/build.yml, setup.py
=> Add GitHub Actions config for automated pypi releases

requests_cache/core.py, tests/test_cache.py
Closes #184. A few PRs later, adding support for this is now pretty simple.
Note that I'll add a bit more documentation for this and other recent changes in a separate 'Advanced Usage' section (#191).
=> Add support for setting different expiration times based on URL patterns

requests_cache/backends/sqlite.py, tests/test_dbdict.py
Closes #119 
It appears these changes were previously contributed by @gorogoroumaru in PR #153, but it didn't get merged.
=> Expose timeout parameter for SQLite backend

docs/advanced_usage.rst, docs/api.rst, docs/index.rst, docs/user_guide.rst, requests_cache/__init__.py, requests_cache/backends/__init__.py, requests_cache/backends/base.py, requests_cache/backends/sqlite.py, requests_cache/core.py, requests_cache/response.py, tests/test_cache.py, tests/test_dbdict.py
=> Add logging to main cache operations

HISTORY.md, requests_cache/backends/__init__.py, requests_cache/backends/base.py, tests/conftest.py, tests/test_cache.py
=> Update remove_expired_responses() to also remove invalid responses

docs/advanced_usage.rst, requests_cache/core.py
The docs didn't match the code.
=> Fix docs for `expire_after_urls` -> `urls_expire_after`

CONTRIBUTING.md, HISTORY.md, docker-compose.yml, docs/Dockerfile, docs/advanced_usage.rst, docs/user_guide.rst
* Added a more detailed example on how to make a custom backend
* Add a couple more ref links
* Added a Dockerfile + docker-compose config to make it easier to setup the readthedocs build environment locally
=> Some more documentation edits and readthedocs container config

setup.py
Installing `tests` package in global scope is just wrong.
=> Do not install "tests" package

HISTORY.md, docs/advanced_usage.rst, requests_cache/__init__.py, requests_cache/backends/__init__.py, requests_cache/backends/base.py, requests_cache/patcher.py, requests_cache/response.py, requests_cache/session.py, tests/unit/test_cache.py
=> Handle errors due to invalid responses in BaseCache.urls

requests_cache/backends/sqlite.py, tests/integration/test_sqlite.py
This PR addresses the issue #213
=> Use thread local connections for sqlite

.gitignore, CONTRIBUTORS.md, HISTORY.md, README.md, docs/user_guide.rst, pyproject.toml, requests_cache/__init__.py, requests_cache/backends/__init__.py, requests_cache/backends/filesystem.py, requests_cache/backends/sqlite.py, tests/integration/test_backends.py, tests/integration/test_filesystem.py, tests/integration/test_thread_safety.py
=> Add a filesystem backend

HISTORY.md, docs/user_guide.rst, requests_cache/patcher.py, requests_cache/session.py, tests/conftest.py, tests/unit/test_cache.py
Closes #210, updates #82
This is mostly done, just need to update the user guide.
=> Handle response error codes with old_data_on_error

HISTORY.md, docs/user_guide.rst, requests_cache/response.py, requests_cache/session.py, tests/unit/test_cache.py, tests/unit/test_patcher.py, tests/unit/test_response.py
Closes #250, #161, updates #192
=> Add support for bypassing the cache if expire_after=0

CONTRIBUTORS.md, HISTORY.md, requests_cache/session.py, tests/integration/base_cache_test.py
=> Add support for caching multipart file uploads

.github/dependabot.yml, .github/pre-commit.yml, .github/workflows/build.yml, docs/conf.py, poetry.lock, pyproject.toml
Also updates to the recently released itsdangerous 2.
=> Add Dependabot V2 config, more pre-commit hooks, and update dev dependencies

docs/advanced_usage.rst
Found some small typos in the RST for describing custom serializers. This small PR fixes it. Nothing more.
Thanks!
=> Fix RST errors in Custom Serializers

.all-contributorsrc, .gitignore, CONTRIBUTORS.md
This PR adds a new contributor list, made with [all-contributors](https://allcontributors.org/). Preview:
=> Generate contributors page using all-contributors

.github/workflows/build.yml, .github/workflows/deploy.yml, .pre-commit-config.yaml, HISTORY.md, README.md, docs/advanced_usage.md, docs/user_guide.md, noxfile.py, poetry.lock, pyproject.toml, requests_cache/__init__.py, requests_cache/backends/base.py, requests_cache/cache_keys.py, requests_cache/core.py, requests_cache/models/response.py, requests_cache/patcher.py, requests_cache/serializers/__init__.py, requests_cache/serializers/cattrs.py, requests_cache/serializers/preconf.py, requests_cache/session.py, tests/integration/base_cache_test.py, tests/integration/test_compat.py, tests/unit/test_serializers.py, tests/unit/test_session.py
Closes #342 
Adding this draft PR now, but will wait at least a week or so to merge it in.
=> Drop support for python 3.6

HISTORY.md, docs/advanced_usage.md, docs/examples.md, examples/custom_cache_keys.py, requests_cache/backends/base.py, requests_cache/cache_keys.py, requests_cache/session.py, tests/unit/test_cache_keys.py, tests/unit/test_session.py
=> Add support for custom cache keys

HISTORY.md, requests_cache/backends/filesystem.py, tests/integration/base_cache_test.py, tests/integration/test_filesystem.py
=> Fix incorrect location of redirects.sqlite when using filesystem backend

HISTORY.md, poetry.lock, requests_cache/__init__.py, requests_cache/backends/__init__.py, requests_cache/backends/base.py, requests_cache/cache_keys.py, requests_cache/serializers/preconf.py, requests_cache/session.py, tests/unit/test_cache_keys.py, tests/unit/test_session.py
=> Allow has_url(), delete_url(), and create_key() to optionally take requests.Request arguments

docs/examples.md, docs/user_guide/compatibility.md
=> Add more library compatibility examples to docs

HISTORY.md, requests_cache/backends/base.py, requests_cache/cache_keys.py, tests/unit/test_cache_keys.py, tests/unit/test_session.py
=> Redact ingored_parameters from CachedResponse.url

HISTORY.md, requests_cache/backends/__init__.py, requests_cache/backends/base.py, requests_cache/session.py, tests/unit/test_session.py
=> Add support for BaseCache keyword arguments passed along with a backend instance

docs/user_guide/serializers.md, requests_cache/serializers/__init__.py, requests_cache/serializers/preconf.py, tests/unit/test_serializers.py
Updates docs, related to issue #452
=> Fix some typos in docs for custom serializers

HISTORY.md, requests_cache/cache_keys.py, tests/unit/test_cache_keys.py
=> Fix request normalization for request body with a list as a JSON root

HISTORY.md, requests_cache/cache_keys.py, tests/unit/test_cache_keys.py
=> Skip normalizing an excessively large JSON request body due to performance impact

docs/user_guide/backends.md, requests_cache/backends/dynamodb.py, requests_cache/backends/filesystem.py, requests_cache/backends/gridfs.py, requests_cache/backends/mongodb.py, requests_cache/backends/redis.py, requests_cache/backends/sqlite.py
=> Add some more docs on when to choose different backends

HISTORY.md, requests_cache/backends/base.py, requests_cache/models/__init__.py, requests_cache/models/response.py, requests_cache/session.py, requests_cache/settings.py, tests/unit/test_session.py
Closes #516 
This required more changes than expected, so I'm on the fence about merging this in. Feedback would be appreciated!
=> Add intermediate wrapper class to provide type hints for extra attributes set on requests.Response objects

HISTORY.md, docs/user_guide/security.md, requests_cache/cache_keys.py, requests_cache/session.py, requests_cache/settings.py, tests/unit/test_session.py
=> Ignore and redact some common authentication headers and parameters by default

HISTORY.md, docs/user_guide/expiration.md, docs/user_guide/headers.md, requests_cache/policy/actions.py, requests_cache/policy/directives.py, requests_cache/policy/settings.py, requests_cache/session.py, tests/unit/policy/test_actions.py, tests/unit/test_session.py
Closes #392, closes #583, closes #592
=> Add support for Cache-Control: max-stale, min-fresh, and stale-if-error

requests_cache/backends/dynamodb.py, requests_cache/backends/filesystem.py, requests_cache/backends/gridfs.py, requests_cache/backends/mongodb.py, requests_cache/backends/redis.py, requests_cache/backends/sqlite.py, requests_cache/models/__init__.py, requests_cache/models/base.py, requests_cache/models/raw_response.py, requests_cache/models/request.py, requests_cache/models/response.py, requests_cache/policy/actions.py, requests_cache/policy/directives.py, requests_cache/policy/settings.py, tests/unit/models/test_base.py
This includes:
* CachedResponse
* CachedRequest
* CachedHTTPRequest
* CacheActions
* CacheDirectives
* CacheSettings
Reference: https://rich.readthedocs.io/en/stable/pretty.html#rich-repr-protocol
=> Improve output for all models when printed or logged with rich

.pre-commit-config.yaml, HISTORY.md, docs/user_guide/backends/dynamodb.md, examples/cloudformation.yml, requests_cache/backends/dynamodb.py
=> Create DynamoDB default table in On Demand mode, add example CloudFormation template

requests_cache/_utils.py, requests_cache/backends/sqlite.py, requests_cache/cache_keys.py, requests_cache/models/raw_response.py, tests/integration/test_filesystem.py, tests/unit/models/test_raw_response.py, tests/unit/models/test_request.py, tests/unit/test_cache_keys.py, tests/unit/test_serializers.py, tests/unit/test_session.py
Updates #605. Coverage (by line count) is now 100%!
=> Add some misc missing test coverage

HISTORY.md, poetry.lock, pyproject.toml, requests_cache/backends/dynamodb.py, requests_cache/backends/gridfs.py, requests_cache/backends/mongodb.py, requests_cache/backends/redis.py, tests/integration/test_mongodb.py
Fix for #611 for 1.0
I will also merge this fix into a patch for 0.9.
=> Fix parameter forwarding for redis-py 4.2 and pymongo 4.1 on python <=3.8

requests_cache/patcher.py
=> Initialize backend with install_cache() prior to patching requests.Session

.gitignore, HISTORY.md, docs/user_guide/expiration.md, docs/user_guide/headers.md, requests_cache/policy/actions.py, requests_cache/policy/directives.py, requests_cache/policy/settings.py, requests_cache/session.py, tests/conftest.py, tests/unit/policy/test_actions.py, tests/unit/test_session.py
=> Implement Cache-Control: stale-while-revalidate

CONTRIBUTING.md, README.md, docs/conf.py, docs/user_guide/advanced_requests.md, docs/user_guide/expiration.md, docs/user_guide/filtering.md, docs/user_guide/general.md, docs/user_guide/inspection.md, docs/user_guide/matching.md, examples/basic_patching.py, examples/basic_sessions.py, examples/log_requests.py, examples/url_patterns.py, examples/vcr.py, poetry.lock, requests_cache/backends/sqlite.py, requests_cache/patcher.py, requests_cache/session.py
=> use https for links

HISTORY.md, requests_cache/models/request.py, tests/unit/models/test_request.py
=> Add CachedRequest.path_url property

HISTORY.md, docs/user_guide/inspection.md, docs/user_guide/matching.md, examples/basic_patching.py, examples/basic_sessions.py, examples/generate_test_db.py, noxfile.py, requests_cache/backends/base.py, requests_cache/backends/filesystem.py, requests_cache/backends/gridfs.py, requests_cache/backends/sqlite.py, requests_cache/cache_keys.py, requests_cache/models/response.py, requests_cache/patcher.py, requests_cache/serializers/pipeline.py, requests_cache/session.py, tests/generate_test_db.py, tests/integration/base_cache_test.py, tests/integration/base_storage_test.py, tests/integration/test_dynamodb.py, tests/integration/test_mongodb.py, tests/integration/test_redis.py, tests/unit/test_base_cache.py, tests/unit/test_patcher.py, tests/unit/test_session.py
Closes #651, updates #643
This required a lot of changes, but I think I'm finally happy with how these look, from both a maintainer and user perspective. These methods seem quite a bit more coherent now.
=> Refactor and consolidate BaseCache convenience methods

docs/examples.md, examples/github_actions.yml
See #663.
Example of a successful run: https://github.com/requests-cache/requests-cache/runs/7419156179?check_suite_focus=true
=> Add example with GitHub Actions

.pre-commit-config.yaml, HISTORY.md, docs/user_guide/matching.md, poetry.lock, requests_cache/backends/base.py, requests_cache/backends/sqlite.py, tests/unit/test_base_cache.py
=> Add method to recreate cache keys

docs/user_guide/expiration.md, docs/user_guide/inspection.md, requests_cache/patcher.py, tests/unit/test_patcher.py
* Add more examples to docs for BaseCache.delete()
* Add `delete()` function for patcher
=> Add docs and wrapper function for BaseCache.delete()

HISTORY.md, docs/user_guide/backends/redis.md, requests_cache/backends/redis.py, tests/integration/test_redis.py
=> Add ttl_offset argument for Redis backend

HISTORY.md, requests_cache/session.py, tests/unit/test_session.py
=> Explicitly disable pickling CachedSession objects

HISTORY.md, requests_cache/policy/directives.py, tests/unit/policy/test_actions.py
=> Add support for header values as bytes

.github/workflows/build.yml, .github/workflows/deploy.yml, .pre-commit-config.yaml, HISTORY.md, docs/user_guide/inspection.md, poetry.lock, pyproject.toml, setup.cfg
* Update to flake8 v6 
* Update other dev dependencies
* Minor edits for cache inspection page
* Add a couple more project links on PyPI
=> Misc updates to docs, tests, and dependencies

HISTORY.md, docs/user_guide/inspection.md, requests_cache/backends/base.py
=> Fix log message and DeprecationWarning (0.9)

HISTORY.md, requests_cache/backends/base.py, requests_cache/backends/dynamodb.py, requests_cache/backends/filesystem.py, requests_cache/backends/gridfs.py, requests_cache/backends/mongodb.py, requests_cache/backends/redis.py, requests_cache/backends/sqlite.py, tests/integration/base_storage_test.py
=> Make CachedResponse.cache_key available from all cache access methods

.github/workflows/deploy.yml
Updates #753 
Reference: https://github.com/snok/install-poetry#running-on-windows
=> Fix tests on Windows

requests_cache/session.py, tests/conftest.py, tests/unit/test_session.py
=> Don't raise_for_status if status_code of response is in allowable_codes

README.md
=> Introduce cache headers and expiration in Readme

HISTORY.md, requests_cache/backends/base.py, requests_cache/backends/sqlite.py, tests/conftest.py, tests/integration/base_cache_test.py, tests/integration/base_storage_test.py, tests/integration/test_sqlite.py
Updates #781 (see issue comments for more details)
=> Share SQLite connection objects among threads, and lock write operations

HISTORY.md, requests_cache/cache_keys.py, tests/unit/test_cache_keys.py
=> Don't normalize CachedResponse.url when redacting ignored params

HISTORY.md, requests_cache/models/response.py, requests_cache/serializers/cattrs.py, tests/conftest.py, tests/integration/base_cache_test.py
=> Fix loading cached JSON content when decode_content=True and the root element is a list

.pre-commit-config.yaml, HISTORY.md, poetry.lock, requests_cache/models/raw_response.py, tests/integration/base_cache_test.py, tests/unit/models/test_raw_response.py
=> Add compatibility with urllib3 2.0

.github/workflows/codeql.yml
Runs weekly on Sunday. See: https://codeql.github.com
=> Add CodeQL scheduled workflow

HISTORY.md, requests_cache/backends/sqlite.py
=> Add locks around SQLite bulk delete operations

HISTORY.md, requests_cache/_utils.py, requests_cache/cache_keys.py, requests_cache/session.py, tests/unit/test_base_cache.py
=> Fix `BaseCache.contains()` for multipart POST requests

requests_cache/backends/sqlite.py, tests/integration/test_sqlite.py
Updates #820 
* This adds a `retries` option to `SQLiteCache`, which determines number of times to retry writing if db is locked (default 3)
* `retries=0` disables retrying
* If not disabled, when the number of retries are exceeded and the db is still locked, the write operation is aborted
* All other db errors are not retried and are re-raised
This is more of a short-term workaround, and not necessarily the best way to handle this, so I'm leaving the option undocumented for now.
=> Allow setting number of times to retry if SQLite db is locked

.pre-commit-config.yaml, HISTORY.md, examples/basic_patching.py, examples/basic_sessions.py, pyproject.toml, requests_cache/__init__.py, requests_cache/backends/__init__.py, requests_cache/models/__init__.py, requests_cache/policy/__init__.py, requests_cache/serializers/__init__.py, requests_cache/serializers/preconf.py, requests_cache/session.py, tests/benchmark_serializers.py, tests/unit/test_base_cache.py, tests/unit/test_session.py
=> Add CachedSession.wrap() method to add caching to an existing Session

.github/workflows/build.yml, .github/workflows/deploy.yml, HISTORY.md, noxfile.py, poetry.lock, pyproject.toml, tests/integration/test_memory.py, tests/integration/test_sqlite.py
=> Add tests for python 3.12

requests_cache/backends/base.py, requests_cache/patcher.py, requests_cache/session.py, tests/unit/test_base_cache.py, tests/unit/test_patcher.py, tests/unit/test_session.py
=> Remove methods deprecated in 1.0

.github/workflows/build.yml, HISTORY.md, requests_cache/models/response.py, requests_cache/policy/settings.py, requests_cache/session.py, tests/unit/models/test_response.py, tests/unit/test_patcher.py, tests/unit/test_session.py
Closes #893 
See issue comments for details. Thanks to @netomi for finding a fix for this!
=> Handle corner case with streaming requests, conditional requests, and redirects

HISTORY.md, requests_cache/cache_keys.py, requests_cache/models/raw_response.py, tests/unit/models/test_raw_response.py, tests/unit/test_cache_keys.py
=> Update `redact_reponse()` to filter details without normalizing

HISTORY.md, requests_cache/cache_keys.py, tests/unit/test_cache_keys.py
=> Handle charset in Content-Type when normalizing request body

requests_cache/backends/__init__.py, requests_cache/backends/filesystem.py, requests_cache/backends/sqlite.py, requests_cache/session.py
=> Add type annotations for Path object used as cache name

HISTORY.md, tests/integration/base_cache_test.py, tests/unit/test_cache_keys.py
Adds tests for #934; updates #927
=> Add tests for updated content-type parsing

docs/user_guide/general.md, docs/user_guide/matching.md, docs/user_guide/troubleshooting.md, requests_cache/backends/gridfs.py, requests_cache/backends/mongodb.py, requests_cache/backends/sqlite.py, requests_cache/patcher.py
=> Fix some doc crossrefs

HISTORY.md, docs/user_guide/serializers.md, poetry.lock, pyproject.toml
Closes #999
Note that I have *not* updated `poetry.lock` which will need to be done after full testing is done.
=> Remove bson dependency

HISTORY.md, requests_cache/serializers/__init__.py, requests_cache/serializers/cattrs.py, requests_cache/serializers/pipeline.py, tests/unit/test_serializers.py
=> Fix issue with multiple serializer objects with different decode_content settings

docs/user_guide/expiration.md, docs/user_guide/matching.md
=> add tip/warning for header variation on cache hits

HISTORY.md, docs/conf.py, docs/user_guide/backends/filesystem.md, requests_cache/backends/filesystem.py, tests/integration/test_filesystem.py
- add documentation
- use lock for creation
- link possible lock options
Closes #603
=> Add lock option for filesystem cache

HISTORY.md, docs/user_guide/backends/filesystem.md, requests_cache/backends/filesystem.py, requests_cache/serializers/__init__.py, requests_cache/serializers/preconf.py, tests/integration/base_storage_test.py, tests/integration/test_filesystem.py
The intention is to close #1050
=> Issue 1050 limit fs cache
